<?php 
$url = $this->GetIframeUrl();
switch($url){
	case 'notbitpay': break; // customer is using another payment method
	case 'paid':
		echo 'Order payment received.  Place Order to complete.'; break;
	case 'disabled':
		echo 'Please click Place Order to continue to bitpay.com.'; break;
	case false:
		echo 'Error creating invoice.  Please try again or try another payment solution.'; break;
	default:
		echo '<iframe src="'.$url.'" style="width: 500px; height: 150px; margin-left: 50px"> </iframe>'; break;
}
$quoteId = $this->GetQuoteId();
?>

<?php
$request = Mage::app()->getRequest();
$url = Mage::getUrl('bitpay_callback/index/checkForPayment/');
if ($request->getScheme() == 'https')
	$url = str_replace('http://', 'https://', $url);
?>
<script type="text/javascript">
//<![CDATA[
new PeriodicalExecuter(function() {new Ajax.Request("<?php echo $url; ?>?quote=<?php echo $quoteId; ?>", {asynchronous:true, evalScripts:true, onComplete:function(request, json) {
	data = request.responseText.evalJSON(); 
	if (data.paid) { 
		buttons = $$("button.btn-checkout");
		buttons.each(function(btn) { btn.click(); })
	} 
}})}, 5);

//]]>
</script>